name: ci

on:
  workflow_dispatch:
  push:
    tags:
    - '*'
  
  pull_request:

jobs:
  build_policy:
    runs-on: ubuntu-latest
    name: build

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
  
    - name: Read policy config
      id: policy-config
      uses: gertd/yaml-reader-action@v1.0
      with:
        file: .github/config-policy.yaml

    - name: Policy Build
      id: policy-build
      uses: opcr-io/policy-build-action@rego_version_input
      with:
        src: content/src
        tag: ${{ steps.policy-config.outputs.repo }}
        revision: "$GITHUB_SHA"
        rego_version: rego.v1
      env:
        POLICY_DEFAULT_DOMAIN: ${{ steps.policy-config.outputs.server }}
