name: publish_template

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:
  publish-template:
    runs-on: ubuntu-latest
    name: build

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Read template config
      id: template-config
      uses: gertd/yaml-reader-action@v1.0
      with:
        file: .github/config-template.yaml

    - name: List Sver Tags
      uses: aserto-dev/sver-action@v0.0.14
      id: "sver"
      with:
        docker_image: ${{ steps.template-config.outputs.repo }}
        docker_registry: ${{ steps.template-config.outputs.server }}
        docker_username: ${{ steps.template-config.outputs.username }}
        docker_password: ${{ secrets.ASERTO_TEMPLATE_PUBLISH_KEY }}

    - name: Oras Login
      id: "oras-login"
      env:
        USERNAME: ${{ steps.template-config.outputs.username }}
        TOKEN:    ${{ secrets.ASERTO_TEMPLATE_PUBLISH_KEY }}
        SERVER:   ${{ steps.template-config.outputs.server }}
      run: |
        oras login -u $USERNAME -p $TOKEN $SERVER

    - name: Compress action step
      id: "compress"
      run: |
        export ROOT_PATH=$PWD
        cd content
        tar -czvf $ROOT_PATH/bundle.tar.gz .
        cd ..

    - name: Oras Push
      id: "oras-push"
      env:
        REPO:   ${{ steps.template-config.outputs.repo }}
        SERVER: ${{ steps.template-config.outputs.server }}
      run: |
       while read -r tag; do
          oras push "${SERVER}/${REPO}:${tag}" \
          --annotation-file ./annotations.json \
          --artifact-type application/vnd.oci.image.layer.v1.tar+gzip ./bundle.tar.gz
        done < <(echo "${{ steps.sver.outputs.version }}")

    - name: Oras Logout
      id: "oras-logout"
      env:
        SERVER: ${{ steps.template-config.outputs.server }}
      run: oras logout $SERVER
